baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "personal-web"

[params]
  intro.main = "Welcome, I'm John Doe"
  intro.sub = "This is my personal website"
  sidebar.logo = "images/edna-west.jpg"